#ifndef MAIN_H_
#define MAIN_H_ MAIN_H_

#include "stm32f7xx_hal.h"

#define REFERENCE_MARK_Pin GPIO_PIN_13
#define REFERENCE_MARK_GPIO_Port GPIOC
#define STEP_SPI_SCK_Pin GPIO_PIN_5
#define STEP_SPI_SCK_GPIO_Port GPIOA
#define STEP_SPI_MISO_Pin GPIO_PIN_6
#define STEP_SPI_MISO_GPIO_Port GPIOA
#define STEP_SPI_MOSI_Pin GPIO_PIN_7
#define STEP_SPI_MOSI_GPIO_Port GPIOA
#define LED_GREEN_Pin GPIO_PIN_0
#define LED_GREEN_GPIO_Port GPIOB
#define STEP_RSTN_Pin GPIO_PIN_12
#define STEP_RSTN_GPIO_Port GPIOF
#define STEP_DIR_Pin GPIO_PIN_13
#define STEP_DIR_GPIO_Port GPIOF
#define STEP_FLAG_Pin GPIO_PIN_15
#define STEP_FLAG_GPIO_Port GPIOF
#define SPINDLE_ENA_BACKWARD_Pin GPIO_PIN_14
#define SPINDLE_ENA_BACKWARD_GPIO_Port GPIOE
#define SPINDLE_ENA_FORWARD_Pin GPIO_PIN_15
#define SPINDLE_ENA_FORWARD_GPIO_Port GPIOE
#define SPINDLE_PWM_FORWARD_Pin GPIO_PIN_10
#define SPINDLE_PWM_FORWARD_GPIO_Port GPIOB
#define SPINDLE_PWM_BACKWARD_Pin GPIO_PIN_11
#define SPINDLE_PWM_BACKWARD_GPIO_Port GPIOB
#define LED_RED_Pin GPIO_PIN_14
#define LED_RED_GPIO_Port GPIOB
#define DEBUG_UART_TX_Pin GPIO_PIN_8
#define DEBUG_UART_TX_GPIO_Port GPIOD
#define DEBUG_UART_RX_Pin GPIO_PIN_9
#define DEBUG_UART_RX_GPIO_Port GPIOD
#define STEP_SPI_CS_Pin GPIO_PIN_14
#define STEP_SPI_CS_GPIO_Port GPIOD
#define LED_BLUE_Pin GPIO_PIN_7
#define LED_BLUE_GPIO_Port GPIOB

#endif /* MAIN_H_ */

